---
name: Pipeline
on: [push]
jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', 3.1]
        gemfile:
        - Gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
        - gemfiles/rails_7.gemfile
        exclude:
        - gemfile: Gemfile
          ruby: 2.5
        - gemfile: gemfiles/rails_7.gemfile
          ruby: 2.5
        - gemfile: Gemfile
          ruby: 2.6
        - gemfile: gemfiles/rails_7.gemfile
          ruby: 2.6
        - gemfile: gemfiles/rails_5.gemfile
          ruby: '3.0'
        - gemfile: gemfiles/rails_5.gemfile
          ruby: 3.1
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.3.26
        bundler-cache: true
    - name: Unit tests
      run: bundle exec rspec
